import { FoodItem, ToolItem, Trophy, StatsForTrophy } from './types';

export const FOOD_ITEMS: FoodItem[] = [
  { name:"卵",             emoji:"🥚", price:30,  category:"基本" },
  { name:"鶏肉",           emoji:"🍗", price:80,  category:"基本" },
  { name:"牛乳",           emoji:"🥛", price:40,  category:"基本" },
  { name:"牛肉",           emoji:"🥩", price:150, category:"基本" },
  { name:"豚肉",           emoji:"🥩", price:100, category:"基本" },
  { name:"玉ねぎ",         emoji:"🧅", price:25,  category:"基本" },
  { name:"小麦粉",         emoji:"🌾", price:20,  category:"基本" },
  { name:"バター",         emoji:"🧈", price:60,  category:"基本" },
  { name:"チーズ",         emoji:"🧀", price:90,  category:"基本" },
  { name:"ベーコン",       emoji:"🥓", price:100, category:"基本" },
  { name:"じゃがいも",     emoji:"🥔", price:30,  category:"野菜" },
  { name:"にんじん",       emoji:"🥕", price:20,  category:"野菜" },
  { name:"ほうれん草",     emoji:"🥬", price:45,  category:"野菜" },
  { name:"キャベツ",       emoji:"🥬", price:30,  category:"野菜" },
  { name:"トマト",         emoji:"🍅", price:40,  category:"野菜" },
  { name:"なす",           emoji:"🍆", price:35,  category:"野菜" },
  { name:"ピーマン",       emoji:"🫑", price:25,  category:"野菜" },
  { name:"きのこ",         emoji:"🍄", price:40,  category:"野菜" },
  { name:"長ねぎ",         emoji:"🧅", price:20,  category:"野菜" },
  { name:"もやし",         emoji:"🌱", price:15,  category:"野菜" },
  { name:"ブロッコリー",   emoji:"🥦", price:50,  category:"野菜" },
  { name:"かぼちゃ",       emoji:"🎃", price:45,  category:"野菜" },
  { name:"大根",           emoji:"🫛", price:25,  category:"野菜" },
  { name:"れんこん",       emoji:"🌀", price:60,  category:"野菜" },
  { name:"鮭",             emoji:"🐟", price:120, category:"魚介" },
  { name:"えび",           emoji:"🦐", price:130, category:"魚介" },
  { name:"いか",           emoji:"🦑", price:110, category:"魚介" },
  { name:"あさり",         emoji:"🐚", price:90,  category:"魚介" },
  { name:"ツナ缶",         emoji:"🐠", price:50,  category:"魚介" },
  { name:"たら",           emoji:"🐡", price:100, category:"魚介" },
  { name:"醤油",           emoji:"🫙", price:30,  category:"調味料" },
  { name:"みりん",         emoji:"🍶", price:35,  category:"調味料" },
  { name:"砂糖",           emoji:"🍬", price:15,  category:"調味料" },
  { name:"トマトケチャップ", emoji:"🍅", price:35, category:"調味料" },
  { name:"味噌",           emoji:"🫙", price:40,  category:"調味料" },
  { name:"マヨネーズ",     emoji:"🥫", price:45,  category:"調味料" },
  { name:"カレー粉",       emoji:"🌶️", price:50,  category:"調味料" },
  { name:"オリーブオイル", emoji:"🫒", price:70,  category:"調味料" },
  { name:"ごま油",         emoji:"🫙", price:55,  category:"調味料" },
  { name:"酢",             emoji:"🧪", price:25,  category:"調味料" },
  { name:"コンソメ",       emoji:"🟡", price:40,  category:"調味料" },
  { name:"めんつゆ",       emoji:"🫙", price:35,  category:"調味料" },
  { name:"ごはん",         emoji:"🍚", price:20,  category:"穀物" },
  { name:"パン粉",         emoji:"🍞", price:25,  category:"穀物" },
  { name:"パスタ",         emoji:"🍝", price:40,  category:"穀物" },
  { name:"うどん",         emoji:"🍜", price:35,  category:"穀物" },
  { name:"そば",           emoji:"🍜", price:45,  category:"穀物" },
  { name:"生クリーム",     emoji:"🥛", price:80,  category:"乳製品" },
  { name:"ヨーグルト",     emoji:"🍦", price:60,  category:"乳製品" },
  { name:"豆腐",           emoji:"⬜", price:35,  category:"その他" },
  { name:"油揚げ",         emoji:"🟡", price:30,  category:"その他" },
  { name:"こんにゃく",     emoji:"🟣", price:30,  category:"その他" },
  { name:"ちくわ",         emoji:"🍢", price:40,  category:"その他" },
  { name:"ハム",           emoji:"🍖", price:80,  category:"その他" },
  { name:"ウインナー",     emoji:"🌭", price:70,  category:"その他" },
  { name:"ナンプラー",     emoji:"🫙", price:60,  category:"エスニック" },
  { name:"ココナッツミルク",emoji:"🥥", price:80, category:"エスニック" },
  { name:"豆板醤",         emoji:"🌶️", price:55,  category:"エスニック" },
  { name:"ニンニク",       emoji:"🧄", price:25,  category:"エスニック" },
  { name:"しょうが",       emoji:"🫚", price:20,  category:"エスニック" },
];

export const TOOL_ITEMS: ToolItem[] = [
  { id:"jade_ladle",      name:"翡翠のオタマ",       emoji:"🥄", price:500,
    effect:"反応イェン×1.5",       desc:"反応イェンが1.5倍になるで！入門の一本やな",
    uses:null, reactionMult:1.5, questMult:1, epicBoost:false, mazuShield:false },
  { id:"gold_pan",        name:"ゴールドのフライパン", emoji:"🍳", price:1500,
    effect:"反応イェン×3 ⚠️1回限り",desc:"めちゃ強いけど金は柔らかいから1回でアウト！",
    uses:1,    reactionMult:3,   questMult:1, epicBoost:false, mazuShield:false },
  { id:"silver_pot",      name:"シルバーの鍋",        emoji:"🫕", price:1200,
    effect:"反応イェン×2 ⚠️3回限り",desc:"銀は丈夫やけど3回使ったら歪んでまうわ〜",
    uses:3,    reactionMult:2,   questMult:1, epicBoost:false, mazuShield:false },
  { id:"diamond_pot",     name:"ダイヤの鍋",          emoji:"💎", price:5000,
    effect:"反応イェン×5",         desc:"最強の鍋！壊れへんで安心して使いや",
    uses:null, reactionMult:5,   questMult:1, epicBoost:false, mazuShield:false },
  { id:"ruby_wok",        name:"ルビーの中華鍋",      emoji:"🔴", price:3000,
    effect:"反応イェン×4",         desc:"炒め物最強！中華料理が得意な鍋やで",
    uses:null, reactionMult:4,   questMult:1, epicBoost:false, mazuShield:false },
  { id:"silk_apron",      name:"シルクのエプロン",    emoji:"👘", price:800,
    effect:"クエストボーナス×2",   desc:"クエスト達成時のボーナスが2倍になるで！",
    uses:null, reactionMult:1,   questMult:2, epicBoost:false, mazuShield:false },
  { id:"velvet_apron",    name:"ビロードのエプロン",  emoji:"🎀", price:2500,
    effect:"クエストボーナス×4",   desc:"最高級の布地！クエストボーナスが4倍やで！",
    uses:null, reactionMult:1,   questMult:4, epicBoost:false, mazuShield:false },
  { id:"platinum_knife",  name:"プラチナ包丁",        emoji:"🔪", price:2000,
    effect:"EPIC排出率アップ",     desc:"料理がEPICになりやすくなるで！",
    uses:null, reactionMult:1,   questMult:1, epicBoost:true,  mazuShield:false },
  { id:"obsidian_knife",  name:"黒曜石の包丁",        emoji:"🗡️", price:3500,
    effect:"EPIC排出率大幅アップ", desc:"火山でできた刃！EPICが爆増するで！",
    uses:null, reactionMult:1,   questMult:1, epicBoost:true,  mazuShield:false },
  { id:"lucky_spatula",   name:"ラッキーヘラ",        emoji:"🍴", price:700,
    effect:"激まず50%防止",        desc:"半分の確率で激まずを回避できるで！",
    uses:null, reactionMult:1,   questMult:1, epicBoost:false, mazuShield:0.5  },
  { id:"magic_tongs",     name:"魔法のトング",        emoji:"✨", price:1800,
    effect:"激まず完全防止 ⚠️5回限り",desc:"激まずにならへん！でも魔法は5回しか使えんで",
    uses:5,    reactionMult:1,   questMult:1, epicBoost:false, mazuShield:1.0  },
  { id:"celestial_ladle", name:"天空のオタマ",        emoji:"🌟", price:8000,
    effect:"全効果×1.5",           desc:"全部1.5倍！反応もクエストもEPICも全部アップやで！",
    uses:null, reactionMult:1.5, questMult:1.5, epicBoost:true, mazuShield:0.3 },
  { id:"phoenix_pan",     name:"不死鳥のフライパン",  emoji:"🦅", price:12000,
    effect:"全効果×2 👑最強",      desc:"幻の道具…反応×2、クエスト×2、EPIC爆増、激まず半減！",
    uses:null, reactionMult:2,   questMult:2, epicBoost:true,  mazuShield:0.5  },
];

export const RARITY: Record<string, { label: string; color: string; bg: string; border: string }> = {
  common:{ label:"COMMON", color:"#888",    bg:"#f5f5f5", border:"#ddd"    },
  rare:  { label:"RARE",   color:"#e05a00", bg:"#fff3ea", border:"#e05a00" },
  epic:  { label:"EPIC",   color:"#d42b2b", bg:"#fff0f0", border:"#d42b2b" },
  mazu:  { label:"激まず", color:"#5a3e00", bg:"#fffbe6", border:"#c8a400" },
};

export const QUEST_BONUS: Record<string, number> = { normal:100, rare:300, special:800 };
export const REACTION_YEN = { fav:3, made:10 };

export const QUEST_GENRES = [
  "和食（煮物・焼き物・揚げ物・丼・麺・汁物など）",
  "洋食（パスタ・グラタン・スープ・ステーキ・シチューなど）",
  "中華（炒め物・餃子・チャーハン・麻婆・春巻きなど）",
  "エスニック（カレー・タイ料理・韓国料理・メキシコ料理など）",
  "お菓子・デザート（ケーキ・クッキー・プリン・パンケーキなど）",
  "おつまみ・軽食（唐揚げ・天ぷら・サラダ・サンドイッチなど）",
  "朝食・ブランチ（卵料理・フレンチトースト・スープなど）",
];

export const QUEST_USERS = [
  "主婦のゆみこ","学生のたろう","料理初心者のけんじ","一人暮らしのはるか",
  "子育て中のさくら","単身赴任のやまだ","料理好きのおじいちゃん","忙しいOLのみか",
  "彼女に作りたいたくみ","お弁当研究中ののり","ダイエット中のあや","男子大学生のそうた",
];

export const TROPHIES: Trophy[] = [
  { id:"cook1",     cat:"料理数",   emoji:"🍳", name:"はじめての一品",   desc:"料理を初めて作った",        check:(s:StatsForTrophy)=>s.totalDishes>=1    },
  { id:"cook5",     cat:"料理数",   emoji:"🥘", name:"5品シェフ",        desc:"料理を5品作った",           check:(s:StatsForTrophy)=>s.totalDishes>=5    },
  { id:"cook10",    cat:"料理数",   emoji:"👨‍🍳", name:"10品の腕前",      desc:"料理を10品作った",          check:(s:StatsForTrophy)=>s.totalDishes>=10   },
  { id:"cook25",    cat:"料理数",   emoji:"🏅", name:"25品マスター",     desc:"料理を25品作った",          check:(s:StatsForTrophy)=>s.totalDishes>=25   },
  { id:"cook50",    cat:"料理数",   emoji:"🥇", name:"50品の達人",       desc:"料理を50品作った",          check:(s:StatsForTrophy)=>s.totalDishes>=50   },
  { id:"cook100",   cat:"料理数",   emoji:"👑", name:"100品の料理王",    desc:"料理を100品作った",         check:(s:StatsForTrophy)=>s.totalDishes>=100  },
  { id:"fav10",     cat:"人気",     emoji:"❤️",  name:"ちょっと人気",    desc:"お気に入り合計10件",        check:(s:StatsForTrophy)=>s.totalFav>=10      },
  { id:"fav50",     cat:"人気",     emoji:"💕", name:"人気レシピ",       desc:"お気に入り合計50件",        check:(s:StatsForTrophy)=>s.totalFav>=50      },
  { id:"fav100",    cat:"人気",     emoji:"💗", name:"100いいね！",      desc:"お気に入り合計100件",       check:(s:StatsForTrophy)=>s.totalFav>=100     },
  { id:"fav300",    cat:"人気",     emoji:"💖", name:"大人気シェフ",     desc:"お気に入り合計300件",       check:(s:StatsForTrophy)=>s.totalFav>=300     },
  { id:"fav1000",   cat:"人気",     emoji:"💎", name:"インフルエンサー", desc:"お気に入り合計1000件",      check:(s:StatsForTrophy)=>s.totalFav>=1000    },
  { id:"made5",     cat:"作った",   emoji:"🥄", name:"参考にしてくれた", desc:"作りました合計5件",         check:(s:StatsForTrophy)=>s.totalMade>=5      },
  { id:"made20",    cat:"作った",   emoji:"🍴", name:"みんなで作った",   desc:"作りました合計20件",        check:(s:StatsForTrophy)=>s.totalMade>=20     },
  { id:"made50",    cat:"作った",   emoji:"🫕", name:"広がるレシピ",     desc:"作りました合計50件",        check:(s:StatsForTrophy)=>s.totalMade>=50     },
  { id:"made100",   cat:"作った",   emoji:"🏆", name:"殿堂入りレシピ",   desc:"作りました合計100件",       check:(s:StatsForTrophy)=>s.totalMade>=100    },
  { id:"made200",   cat:"作った",   emoji:"⭐", name:"伝説のレシピ",     desc:"作りました合計200件",       check:(s:StatsForTrophy)=>s.totalMade>=200    },
  { id:"quest1",    cat:"クエスト", emoji:"⚔️", name:"初クエスト達成",   desc:"クエストを初めて達成した",  check:(s:StatsForTrophy)=>s.questClear>=1     },
  { id:"quest3",    cat:"クエスト", emoji:"🗡️", name:"クエストクリア常連",desc:"クエストを3回達成した",    check:(s:StatsForTrophy)=>s.questClear>=3     },
  { id:"quest10",   cat:"クエスト", emoji:"🛡️", name:"クエストマスター", desc:"クエストを10回達成した",    check:(s:StatsForTrophy)=>s.questClear>=10    },
  { id:"quest20",   cat:"クエスト", emoji:"🏰", name:"伝説の冒険者",     desc:"クエストを20回達成した",    check:(s:StatsForTrophy)=>s.questClear>=20    },
  { id:"qspecial1", cat:"クエスト", emoji:"🌟", name:"SPクリア！",       desc:"SPECIALクエストを達成した", check:(s:StatsForTrophy)=>s.questSpecial>=1   },
  { id:"qspecial3", cat:"クエスト", emoji:"✨", name:"SP三冠",           desc:"SPECIALクエストを3回達成",  check:(s:StatsForTrophy)=>s.questSpecial>=3   },
  { id:"yen500",    cat:"イェン",   emoji:"💰", name:"初めての稼ぎ",     desc:"累計¥500獲得",              check:(s:StatsForTrophy)=>s.totalEarned>=500  },
  { id:"yen2000",   cat:"イェン",   emoji:"💵", name:"¥2000の壁",        desc:"累計¥2000獲得",             check:(s:StatsForTrophy)=>s.totalEarned>=2000 },
  { id:"yen5000",   cat:"イェン",   emoji:"💴", name:"お金持ちシェフ",   desc:"累計¥5000獲得",             check:(s:StatsForTrophy)=>s.totalEarned>=5000 },
  { id:"yen10000",  cat:"イェン",   emoji:"💸", name:"一万円シェフ",     desc:"累計¥10000獲得",            check:(s:StatsForTrophy)=>s.totalEarned>=10000},
  { id:"yen50000",  cat:"イェン",   emoji:"🏦", name:"億り人への道",     desc:"累計¥50000獲得",            check:(s:StatsForTrophy)=>s.totalEarned>=50000},
  { id:"rare1",     cat:"レアリティ",emoji:"🟠", name:"初RARE",          desc:"RARE料理を初めて作った",    check:(s:StatsForTrophy)=>s.rareCount>=1      },
  { id:"rare5",     cat:"レアリティ",emoji:"🔶", name:"RARE常連",        desc:"RARE料理を5品作った",       check:(s:StatsForTrophy)=>s.rareCount>=5      },
  { id:"rare10",    cat:"レアリティ",emoji:"🧡", name:"RAREマスター",    desc:"RARE料理を10品作った",      check:(s:StatsForTrophy)=>s.rareCount>=10     },
  { id:"epic1",     cat:"レアリティ",emoji:"🔴", name:"初EPIC！",        desc:"EPIC料理を初めて作った",    check:(s:StatsForTrophy)=>s.epicCount>=1      },
  { id:"epic5",     cat:"レアリティ",emoji:"❤️‍🔥", name:"EPICハンター",  desc:"EPIC料理を5品作った",       check:(s:StatsForTrophy)=>s.epicCount>=5      },
  { id:"epic10",    cat:"レアリティ",emoji:"💥", name:"EPIC王",          desc:"EPIC料理を10品作った",      check:(s:StatsForTrophy)=>s.epicCount>=10     },
  { id:"mazu1",     cat:"激まず",   emoji:"🤢", name:"失敗は成功のもと", desc:"激まずを初めて作った",      check:(s:StatsForTrophy)=>s.mazuCount>=1      },
  { id:"mazu5",     cat:"激まず",   emoji:"🤮", name:"5回失敗",          desc:"激まずを5回作った",         check:(s:StatsForTrophy)=>s.mazuCount>=5      },
  { id:"mazu10",    cat:"激まず",   emoji:"💀", name:"失敗の達人",       desc:"激まずを10回作った",        check:(s:StatsForTrophy)=>s.mazuCount>=10     },
  { id:"trash5",    cat:"激まず",   emoji:"🗑️", name:"掃除好き",         desc:"激まずを5回捨てた",         check:(s:StatsForTrophy)=>s.trashCount>=5     },
  { id:"tool1",     cat:"道具",     emoji:"🥄", name:"道具デビュー",     desc:"道具を初めて購入した",      check:(s:StatsForTrophy)=>s.toolCount>=1      },
  { id:"tool3",     cat:"道具",     emoji:"🍴", name:"道具コレクター",   desc:"道具を3種類購入した",       check:(s:StatsForTrophy)=>s.toolCount>=3      },
  { id:"tool7",     cat:"道具",     emoji:"🔪", name:"道具マニア",       desc:"道具を7種類購入した",       check:(s:StatsForTrophy)=>s.toolCount>=7      },
  { id:"goldbroke", cat:"道具",     emoji:"😭", name:"金は柔らかい",     desc:"ゴールドのフライパンを使い切った", check:(s:StatsForTrophy)=>s.goldUsed>=1 },
  { id:"legendary", cat:"道具",     emoji:"🦅", name:"不死鳥の主人",     desc:"不死鳥のフライパンを購入した",    check:(s:StatsForTrophy)=>s.hasFenix      },
  { id:"first_post",cat:"特殊",     emoji:"📣", name:"初投稿！",         desc:"レシピを初めて投稿した",    check:(s:StatsForTrophy)=>s.totalDishes>=1    },
  { id:"combo3",    cat:"特殊",     emoji:"🔗", name:"3食材コンボ",      desc:"3種類以上でマージした",     check:(s:StatsForTrophy)=>s.maxCombo>=3       },
  { id:"combo5",    cat:"特殊",     emoji:"💫", name:"5食材コンボ！",    desc:"5種類以上でマージした",     check:(s:StatsForTrophy)=>s.maxCombo>=5       },
  { id:"night_cook",cat:"特殊",     emoji:"🌙", name:"夜食シェフ",       desc:"深夜0時以降に料理した",     check:(s:StatsForTrophy)=>s.nightCook>=1      },
  { id:"speed3",    cat:"特殊",     emoji:"⚡", name:"スピードシェフ",   desc:"1分以内に3品作った",        check:(s:StatsForTrophy)=>s.speedCook>=1      },
  { id:"all_cat",   cat:"特殊",     emoji:"🌈", name:"全ジャンル制覇",   desc:"和洋中エスニック全部作った",check:(s:StatsForTrophy)=>s.allGenre          },
  { id:"notrash10", cat:"特殊",     emoji:"🧹", name:"無駄なし職人",     desc:"激まずなしで10品連続",      check:(s:StatsForTrophy)=>s.noMazuStreak>=10  },
  { id:"rich",      cat:"特殊",     emoji:"🤑", name:"大富豪",           desc:"所持イェンが¥10000超",      check:(s:StatsForTrophy)=>s.currentYen>=10000 },
  { id:"shop10",    cat:"特殊",     emoji:"🛒", name:"爆買いシェフ",     desc:"食材を10回以上購入",        check:(s:StatsForTrophy)=>s.shopCount>=10     },
  { id:"complete",  cat:"特殊",     emoji:"🎊", name:"コンプリート！",   desc:"他のトロフィーを40個以上獲得",check:(s:StatsForTrophy)=>s.trophyCount>=40  },
];
